### ISSUE TITLE
2nd Review - Sprint 1

### ISSUE THREAD

**Issue by NicolasGlassey** [AMT-TEAM09/AMT-TestAws#4]
@GeraudSilvestri  @BernardLhermite 

Bonjour Messieurs,

J'ai relu la classe de test que vous aviez modifié suite à mes retours (qui sont plus des propositions que des "erreurs" à corriger").

https://github.com/AMT-TEAM09/AMT-Labelizer/pull/2

Voici mes observations:
[] La factorisation dans setup et teardown a été réalisée - ok
[] Certaines signatures de méthodes ne contiennent pas le scenario. Vous mentionnez le nom de la méthode, et le résultat attendu. @BernardLhermite  était en train de recoder les tests en partant de la classe de tests livrés pour le sprint 2, donc ce problème est certainement déjà corrigé.
[] Je remarque aussi que vous avez prévu des cas de tests qui n'étaient pas demandés. Svp ne les supprimez pas ! Je les prendrai en compte comme bonus. Exemple : Le test gérant la durée de vie négative du lien de publication ;).
[] Concernant l'utilisation de "assertDoesNotThrow(()", j'ai ouvert une discussion entre Hadrien et Stéphane sur Teams. De votre côté, vous vérifiez bien la bonne création de l'objet avec DoesExist après la création. Donc ok.
[] La méthode delete du SDK ne notifie rien lorsque l'on tente de supprimer un objet inexistant. Dans votre propre méthode de suppression d'objet, un appel a "DoesExist" pour valider les préconditions fait sens, avant de tenter une suppression. Ainsi votre méthode delete pourra lever votre exception "NoSuchObejctException".
[] Il serait également bien d'ajouter un niveau d'exception. Vous faites hériter NoSuchObjectException directement depuis l'exception standard de Java. Un parent du genre "AwsDataObjectHelperException" dont votre propre exception hérite permettrait une meilleure compréhension de la provenance de l'exception pour celui qui debug.

Bonne suite de projet !
Nicolas Glassey

**Comment by BernardLhermite** [comment]
@NicolasGlassey 

Bonjour,

Merci pour le retour.

Le point 2 devrait effectivement être corrigé.

Des exceptions spécialisées ont aussi été rajoutées comme mentionné dans vos 2 derniers points lors de la modification du service suite à la réécriture des tests.
